# Generated by Django 5.2.7 on 2025-12-08 14:25

import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "modalidade",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("presencial", "Presencial"),
                            ("hibrido", "Híbrido"),
                        ],
                        max_length=10,
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("horario", models.TimeField()),
                ("local", models.CharField(blank=True, max_length=200, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "quantidade_participantes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("sem_limites", models.BooleanField(default=False)),
                (
                    "organizador",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "thumb",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=eventos.models.Evento.evento_thumb_upload_to,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "horas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "gallery_slug",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("finalizado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="InscricaoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_validated", models.BooleanField(default=False)),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
