# Generated by Django 5.2.7 on 2025-10-09 19:18

# Este arquivo foi gerado automaticamente pelo Django em 09/10/2025.
# Ele faz alterações no banco de dados, adicionando novos campos e ajustando relações entre modelos.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # Define as migrações anteriores que esta depende.
    # Isso garante que essas migrações sejam aplicadas antes desta.
    dependencies = [
        ("eventos", "0001_initial"),  # Depende da migração inicial do app "eventos"
        ("usuarios", "0012_usuario_user_alter_usuario_senha"),  # Depende da migração 0012 do app "usuarios"
    ]

    # Lista de operações que serão aplicadas ao banco de dados
    operations = [
        # Adiciona um novo campo "criador" ao modelo "Evento"
        migrations.AddField(
            model_name="evento",  # Nome do modelo que receberá o novo campo
            name="criador",       # Nome do campo que será adicionado
            field=models.ForeignKey(
                # Permite que o campo fique vazio (sem criador definido)
                blank=True,
                null=True,

                # Se o usuário criador for excluído, o campo "criador" será definido como NULL
                # Isso evita apagar o evento junto com o usuário.
                on_delete=django.db.models.deletion.SET_NULL,

                # Define um nome alternativo para acessar os eventos criados a partir do usuário
                # Exemplo: usuario.eventos_criados.all() retorna todos os eventos criados por aquele usuário
                related_name="eventos_criados",

                # Define o modelo de destino dessa relação (app "usuarios", modelo "Usuario")
                to="usuarios.usuario",
            ),
        ),

        # Altera o campo "aluno" no modelo "InscricaoEvento"
        migrations.AlterField(
            model_name="inscricaoevento",
            name="aluno",
            field=models.ForeignKey(
                # Se o aluno for deletado, suas inscrições também serão removidas
                on_delete=django.db.models.deletion.CASCADE,

                # Define que o campo agora aponta para o modelo "Usuario" (do app "usuarios")
                to="usuarios.usuario",
            ),
        ),
    ]
