# Generated by Django 5.2.7 on 2025-12-08 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventos", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="criador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_criados",
                to="usuarios.usuario",
            ),
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eventos.evento"
            ),
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="inscrito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.usuario"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eventos.tipoevento"
            ),
        ),
    ]
