# Generated by Django 5.2.7 on 2025-10-09 20:11

# Este arquivo foi gerado automaticamente pelo Django em 09/10/2025.
# Ele faz alterações no modelo "Evento" e renomeia um campo no modelo "TipoEvento".

from django.db import migrations, models


class Migration(migrations.Migration):
    # Define de quais migrações anteriores este arquivo depende.
    # Isso garante que todas as mudanças anteriores estejam aplicadas antes desta.
    dependencies = [
        ("eventos", "0002_evento_criador_alter_inscricaoevento_aluno"),
    ]

    # Lista de operações que serão aplicadas ao banco de dados.
    operations = [
        # 1️⃣ Renomeia um campo na tabela "TipoEvento"
        migrations.RenameField(
            model_name="tipoevento",  # Nome do modelo afetado
            old_name="nome",           # Nome atual do campo no banco
            new_name="tipo",           # Novo nome que o campo passará a ter
        ),

        # 2️⃣ Adiciona um novo campo booleano "sem_limites" na tabela "Evento"
        migrations.AddField(
            model_name="evento",       # Modelo que receberá o novo campo
            name="sem_limites",        # Nome do campo que será criado
            field=models.BooleanField(
                default=False           # Valor padrão (False = evento com limite de participantes)
            ),
        ),

        # 3️⃣ Altera o campo "organizador" em "Evento"
        migrations.AlterField(
            model_name="evento",
            name="organizador",
            field=models.CharField(
                max_length=200,        # Tamanho máximo do texto
                blank=True,             # Campo pode ser deixado em branco nos formulários
                null=True,              # Campo pode ser nulo no banco de dados
            ),
        ),

        # 4️⃣ Altera o campo "quantidade_participantes" em "Evento"
        migrations.AlterField(
            model_name="evento",
            name="quantidade_participantes",
            field=models.PositiveIntegerField(
                blank=True,             # Campo opcional no formulário
                null=True,              # Campo pode ser nulo no banco de dados
            ),
        ),
    ]
