# Generated by Django 5.2.7 on 2025-10-09 20:59

# Este arquivo foi gerado automaticamente pelo Django em 09/10/2025.
# Ele adiciona dois novos campos: um para imagem de capa (thumb) nos eventos,
# e outro para indicar se uma inscrição foi validada.

from django.db import migrations, models


class Migration(migrations.Migration):
    # Define de quais migrações anteriores este arquivo depende.
    # Isso garante que todas as alterações anteriores estejam aplicadas antes desta.
    dependencies = [
        ("eventos", "0003_rename_nome_tipoevento_tipo_evento_sem_limites_and_more"),
    ]

    # Lista das operações que o Django aplicará ao banco de dados.
    operations = [
        # 1️⃣ Adiciona o campo "thumb" (miniatura / imagem de capa) ao modelo "Evento"
        migrations.AddField(
            model_name="evento",       # Modelo que receberá o novo campo
            name="thumb",              # Nome do campo
            field=models.ImageField(
                blank=True,            # Campo pode ser deixado em branco nos formulários
                null=True,             # Campo pode ser nulo no banco de dados
                upload_to="eventos/thumbnails/",  # Caminho onde a imagem será salva (dentro da pasta 'media/')
            ),
        ),

        # 2️⃣ Adiciona o campo "is_validated" ao modelo "InscricaoEvento"
        migrations.AddField(
            model_name="inscricaoevento",  # Modelo que receberá o campo
            name="is_validated",           # Nome do campo
            field=models.BooleanField(
                default=False,             # Valor padrão é False (inscrição ainda não validada)
            ),
        ),
    ]
