# Generated by Django 5.2.7 on 2025-10-09 22:44

# Este arquivo foi gerado automaticamente pelo Django em 09/10/2025.
# Ele adiciona um novo campo ao modelo "Evento" chamado "finalizado",
# que serve para indicar se o evento já foi encerrado ou ainda está ativo.

from django.db import migrations, models


class Migration(migrations.Migration):
    # Define de quais migrações anteriores este arquivo depende.
    # Assim, o Django aplica todas as alterações anteriores antes desta.
    dependencies = [
        ("eventos", "0004_evento_thumb_inscricaoevento_is_validated"),
    ]

    # Lista das operações que serão executadas no banco de dados.
    operations = [
        # 1️⃣ Adiciona o campo "finalizado" ao modelo "Evento"
        migrations.AddField(
            model_name="evento",       # Nome do modelo que receberá o novo campo
            name="finalizado",         # Nome do campo a ser criado
            field=models.BooleanField(
                default=False,         # Valor padrão: False (evento ainda não finalizado)
            ),
        ),
    ]
