# Generated by Django 5.2.7 on 2025-10-10 02:59

# Este arquivo foi gerado automaticamente pelo Django em 10/10/2025.
# Ele adiciona dois novos campos ao modelo "Evento": "descricao" e "gallery_slug".

from django.db import migrations, models


class Migration(migrations.Migration):
    # Define de quais migrações anteriores este arquivo depende.
    # Isso garante que todas as migrações anteriores sejam aplicadas antes desta.
    dependencies = [
        ("eventos", "0005_evento_finalizado"),
    ]

    # Lista das operações que o Django executará no banco de dados.
    operations = [
        # 1️⃣ Adiciona o campo "descricao" ao modelo "Evento"
        migrations.AddField(
            model_name="evento",     # Nome do modelo que receberá o novo campo
            name="descricao",        # Nome do campo
            field=models.TextField(
                blank=True,          # Campo pode ser deixado em branco nos formulários
                null=True,           # Campo pode ser nulo no banco de dados
            ),
        ),

        # 2️⃣ Adiciona o campo "gallery_slug" ao modelo "Evento"
        migrations.AddField(
            model_name="evento",     # Modelo afetado
            name="gallery_slug",     # Nome do novo campo
            field=models.CharField(
                max_length=255,      # Tamanho máximo de caracteres
                blank=True,          # Campo opcional nos formulários
                null=True,           # Campo pode ser nulo no banco
            ),
        ),
    ]
