# Generated by Django 5.2.7 on 2025-10-10 03:56

# Este arquivo foi gerado automaticamente pelo Django em 10/10/2025.
# Ele adiciona um novo campo chamado "horas" ao modelo "Evento".

from django.db import migrations, models  # Importa funções e classes necessárias para criar migrações

class Migration(migrations.Migration):
    # Define de quais migrações anteriores esta depende.
    # Isso garante que todas as alterações anteriores sejam aplicadas antes desta.
    dependencies = [
        ("eventos", "0006_evento_descricao_evento_gallery_slug"),
    ]

    # Lista de operações que o Django executará no banco de dados
    operations = [
        # 1️⃣ Adiciona o campo "horas" ao modelo "Evento"
        migrations.AddField(
            model_name="evento",     # Nome do modelo que receberá o novo campo
            name="horas",            # Nome do campo
            field=models.DecimalField(
                max_digits=5,        # Total de dígitos permitidos (ex: 123.45 → 5 dígitos)
                decimal_places=2,    # Número de casas decimais (2 → permite frações de hora como 1.50)
                blank=True,          # Campo opcional em formulários (não precisa ser preenchido)
                null=True,           # Campo opcional no banco de dados (pode ser nulo)
            ),
        ),
    ]
