# Generated by Django 5.2.7 on 2025-10-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0007_evento_horas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="horas",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duração do evento em horas", null=True
            ),
        ),
    ]
