# Generated by Django 5.2.7 on 2025-10-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0008_alter_evento_horas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="horas",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
