# Generated by Django 5.2.7 on 2025-10-11 04:39

import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0009_alter_evento_horas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="thumb",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=eventos.models.Evento.evento_thumb_upload_to,
            ),
        ),
    ]
