# Generated by Django 5.2.7 on 2025-10-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0010_alter_evento_thumb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inscricaoevento",
            old_name="aluno",
            new_name="inscrito",
        ),
    ]
