# Generated by Django 5.2.7 on 2025-10-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_instituicao_usuario_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="DDD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=5, unique=True)),
                ("pais", models.CharField(default="Brasil", max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="ddd",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
