# Generated by Django 5.2.7 on 2025-10-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_ddd_usuario_ddd_alter_usuario_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ddd",
            name="codigo",
            field=models.CharField(max_length=5),
        ),
    ]
