# Generated by Django 5.2.7 on 2025-10-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_alter_ddd_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ddd",
            name="codigo",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
