# Generated by Django 5.2.7 on 2025-10-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_alter_ddd_codigo"),
    ]

    operations = []
