# Generated by Django 5.2.7 on 2025-10-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0008_remove_unique_ddd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="ddd",
            field=models.CharField(blank=True, null=True),
        ),
    ]
