# Generated by Django 5.2.7 on 2025-10-09 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0009_alter_usuario_ddd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="ddd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usuarios.ddd",
            ),
        ),
    ]
