# Generated by Django 5.2.7 on 2025-10-09 18:46

import django.db.models.deletion
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0010_alter_usuario_ddd"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="biografia",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(upload_to=usuarios.models.user_directory_path),
                ),
                ("nome", models.CharField(blank=True, max_length=200)),
                ("data_emitido", models.DateField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
