# Generated by Django 5.2.7 on 2025-10-09 20:59

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0012_usuario_user_alter_usuario_senha"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificado",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to=usuarios.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="certificado",
            name="png",
            field=models.ImageField(
                blank=True, null=True, upload_to=usuarios.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="certificado",
            name="qr_data",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="certificado",
            name="arquivo",
            field=models.FileField(
                blank=True, null=True, upload_to=usuarios.models.user_directory_path
            ),
        ),
    ]
