# Generated by Django 5.2.7 on 2025-10-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usuarios",
            "0013_certificado_pdf_certificado_png_certificado_qr_data_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="instituicao",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="instituicao",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="perfil",
            name="mostrar_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="perfil",
            name="mostrar_telefone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
