# Generated by Django 5.2.7 on 2025-10-09 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0005_evento_finalizado"),
        ("usuarios", "0014_instituicao_email_instituicao_telefone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificado",
            name="evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eventos.evento",
            ),
        ),
    ]
