# Generated by Django 5.2.7 on 2025-10-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0015_certificado_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="base_dir",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
