# Generated by Django 5.2.7 on 2025-10-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0016_usuario_base_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificado",
            name="horas",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="certificado",
            name="public_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
