# Generated by Django 5.2.7 on 2025-12-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='telefone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
